/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_matejhrazdira_cbsample_Sample */

#ifndef _Included_com_matejhrazdira_cbsample_Sample
#define _Included_com_matejhrazdira_cbsample_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_matejhrazdira_cbsample_Sample
 * Method:    initCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_matejhrazdira_cbsample_Sample_initCache
  (JNIEnv *, jclass);

/*
 * Class:     com_matejhrazdira_cbsample_Sample
 * Method:    copyUnion
 * Signature: (Lcom/matejhrazdira/cbsample/generated/SimpleIdl/SimpleUnion;)Lcom/matejhrazdira/cbsample/generated/SimpleIdl/SimpleUnion;
 */
JNIEXPORT jobject JNICALL Java_com_matejhrazdira_cbsample_Sample_copyUnion
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
